name: Build .unitypackage

on:
  pull_request:
  workflow_dispatch:

jobs:
  package_unity:
    runs-on: ubuntu-latest
    env:
      UNITY_PACKAGE: test2.unitypackage

    steps:
    - name: Publish test .unitypackage
      uses: MirrorNG/unity-runner@3.1.0
      with:
        args: |
          -username ${{ secrets.VRY_SECRET }}
          -password ${{ secrets.VRY_SECRET }}
          -serial ${{ secrets.VRY_SECRET }}
          -gvh_disable
          -batchmode
          -nographics
          -silent-crashes
          -importPackage ./ThirdParty/external-dependency-manager-1.2.164.unitypackage
          -projectPath ./
          -executeMethod Publishing.PublishFromCommandLine
          -quit $UNITY_PACKAGE
