name: Build .unitypackage

on:
  pull_request:
  workflow_dispatch:

jobs:
  package_unity:
    runs-on: ubuntu-latest
    env:
      UNITY_PACKAGE: test2.unitypackage

    steps:
    - name: Publish test .unitypackage
      uses: MirrorNG/unity-runner@3.1.0
      with:
        -username ${{ secrets.VRY_SECRET }}
        -password ${{ secrets.VRY_SECRET }}
        -serial ${{ secrets.VRY_SECRET }}
        -quit $UNITY_PACKAGE

    - name: log action output
      run: echo ${{steps.run_action.outputs.my_output}} 
